### ISSUE TITLE
Data fetching incorrect

### ISSUE THREAD

**Issue by LukeGotBored** [Kylart/MalScraper#39] opened 2020-08-31 12:52 UTC
Some data in the anime JSON returns incorrect
some examples are "title" that return "Top"
and picture, that returns undefined

**Comment by SammyWhamy** [comment] 2020-08-31 15:29
This was already fixed (For me at least) in 2.7.2

**Comment by Kylart** [comment] 2020-08-31 22:29
Duplicate of #37 . This is fixed in 2.7.2

**Closed by Kylart** 2020-08-31 22:29 UTC
